use types::{ArchivedTestStruct, TestStruct};

const ROUTES_ARCHIVE: &[u8] = include_bytes!(concat!(env!("OUT_DIR"), "/routes.rkyv"));

pub fn load_routes() -> &'static ArchivedTestStruct {
    // SAFETY: this archive is guaranteed to be valid, as it is generated by the
    // build script and loaded from the binary itself
    unsafe { TestStruct::access_unchecked(ROUTES_ARCHIVE) }
}

pub fn run() {
    let test = load_routes();
    println!("text: {}", test.text);
    println!("{test:?}");
}
