pub mod types;

use rkyv::util::Align;

pub use types::{ArchivedJourney, ArchivedJourneys, ArchivedRouteDetails, ArchivedStopDetails};

// Embed the archive with 16-byte alignment to satisfy rkyv's access requirements
static ALIGNED_ARCHIVE: Align<[u8; include_bytes!(concat!(env!("OUT_DIR"), "/journeys.rkyv")).len()]> =
    Align(*include_bytes!(concat!(env!("OUT_DIR"), "/journeys.rkyv")));

pub fn load_routes() -> &'static ArchivedJourneys {
    // SAFETY: this archive is guaranteed to be valid, as it is generated by the
    // build script and loaded from the binary itself
    unsafe { types::Journeys::access_unchecked(ALIGNED_ARCHIVE.as_ref()) }
}
